SELECT p.PRODUCT_CODE, SUM(p.PRICE * os.SALES_AMOUNT) AS TOTAL_SALES
FROM PRODUCT p
INNER JOIN OFFLINE_SALE os ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY TOTAL_SALES DESC, p.PRODUCT_CODE;
