SELECT
    b.TITLE AS BOARD_TITLE,
    b.BOARD_ID,
    r.REPLY_ID,
    r.WRITER_ID AS REPLY_WRITER_ID,
    r.CONTENTS AS REPLY_CONTENTS,
    DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS REPLY_CREATED_DATE
FROM
    USED_GOODS_BOARD b
JOIN
    USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
WHERE
    DATE_FORMAT(b.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY
    REPLY_CREATED_DATE ASC, BOARD_TITLE ASC;
